### ISSUE TITLE
Show repository as a link

### ISSUE THREAD

**Issue by suneev** [ERS-HCL/gatsby-demo-app#3]
When showing the list of repositories, the repository name should hyperlink to the project

**Comment by tsukhu** [comment]
This has been fixed
* Added a new react-table 
* Now we have the ability to paginate the table, sort 
* There is a link added to each row which give the short description as well as provides a link to the github project
![issue 3 fix](https://user-images.githubusercontent.com/846306/36203387-6987b268-11ad-11e8-994f-5950ba598b46.PNG)
* The output is available on https://ers-hcl.github.io/
