### ISSUE TITLE
Separate page for whitepapers

### ISSUE THREAD

**Issue by suneev** [ERS-HCL/gatsby-demo-app#4]
It may be better to show the list of whitepapers on a separate page since we have accumulated a large number of whitepapers (currently available from https://kx.hcl.com/sites/TechOffice/Publication)

**Comment by tsukhu** [comment]
@suneev  The purpose of the post is primarily just a news item or some new information about the projects/technologies used. The ones put in now were just samples and can be removed it not appropriate . We can also have that as a separate page where we import data from an xls and then show it on another page .. 
Effort required

- Use the XLS source plugin to pull the data
- Create a new react page component
- Pull date from xls via graphQL
- Display table

**Comment by suneev** [comment]
Pls create a separate challenge (if not already done) for creating the pagination from xls as per the steps you have described.

**Comment by tsukhu** [comment]
Fixed
